/**
 * Script to generate snippet-templates.ts from actual component implementations.
 * Run: pnpm generate-snippets (from apps/docs)
 *
 * Reads source files from packages/{mantine,antd,shadcn}/src/components/
 * and generates apps/docs/src/data/snippet-templates.ts with embedded implementations.
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

type Framework = "mantine" | "antd" | "shadcn";

const ROOT_DIR = join(import.meta.dirname, "..", "..", "..");
const PACKAGES_DIR = join(ROOT_DIR, "packages");
const OUTPUT_FILE = join(
  ROOT_DIR,
  "apps",
  "docs",
  "src",
  "data",
  "snippet-templates.ts",
);

const FRAMEWORK_DIRS: Record<Framework, string> = {
  mantine: "mantine",
  antd: "antd",
  shadcn: "shadcn",
};

function getComponentSource(
  framework: Framework,
  componentName: string,
): string {
  const dir = FRAMEWORK_DIRS[framework];
  const filePath = join(
    PACKAGES_DIR,
    dir,
    "src",
    "components",
    componentName,
    `${componentName}.tsx`,
  );

  try {
    return readFileSync(filePath, "utf-8");
  } catch {
    return `// Component not found: ${framework}/${componentName}`;
  }
}

function escapeTemplateString(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
}

function generateSnippetTemplates(): void {
  const componentsDir = join(PACKAGES_DIR, "mantine", "src", "components");
  const patterns = readdirSync(componentsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  const entries: string[] = [];

  for (const pattern of patterns) {
    const mantine = escapeTemplateString(
      getComponentSource("mantine", pattern),
    );
    const antd = escapeTemplateString(getComponentSource("antd", pattern));
    const shadcn = escapeTemplateString(getComponentSource("shadcn", pattern));

    entries.push(`"${pattern}": {
    mantine: \`${mantine}\`,
    antd: \`${antd}\`,
    shadcn: \`${shadcn}\`,
  }`);
  }

  const content = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-snippets.ts
 * Run: pnpm generate-snippets
 */

export const codeSnippets: Record<
  string,
  { mantine: string; antd: string; shadcn: string }
> = {
${entries.join(",\n")}
};
 `;

  writeFileSync(OUTPUT_FILE, content, "utf-8");
  // eslint-disable-next-line no-console
  console.log(`Generated ${OUTPUT_FILE}`);
  // eslint-disable-next-line no-console
  console.log(`Patterns: ${String(patterns.length)}`);
  // eslint-disable-next-line no-console
  console.log(`Frameworks: mantine, antd, shadcn`);
}

generateSnippetTemplates();
