/**
 * Script to generate snippet-templates.ts from actual component implementations.
 * Run: pnpm generate-snippets (from apps/docs)
 *
 * Reads source files from packages/{bootstrap,antd,mantine}/src/components/
 * and generates apps/docs/src/data/snippet-templates.ts with embedded implementations.
 */

import { readFileSync, writeFileSync, readdirSync } from "fs";
import { join } from "path";

type Framework = "bootstrap" | "antd" | "mantine";

const ROOT_DIR = join(import.meta.dirname, "..", "..", "..");
const PACKAGES_DIR = join(ROOT_DIR, "packages");
const OUTPUT_FILE = join(
  ROOT_DIR,
  "apps",
  "docs",
  "src",
  "data",
  "snippet-templates.ts",
);

const FRAMEWORK_DIRS: Record<Framework, string> = {
  bootstrap: "bootstrap",
  antd: "antd",
  mantine: "mantine",
};

function getComponentSource(
  framework: Framework,
  componentName: string,
): string {
  const dir = FRAMEWORK_DIRS[framework];
  const filePath = join(
    PACKAGES_DIR,
    dir,
    "src",
    "components",
    componentName,
    `${componentName}.tsx`,
  );

  try {
    return readFileSync(filePath, "utf-8");
  } catch {
    return `// Component not found: ${framework}/${componentName}`;
  }
}

function escapeTemplateString(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
}

function generateSnippetTemplates(): void {
  // Get all pattern directories from bootstrap package
  const componentsDir = join(PACKAGES_DIR, "bootstrap", "src", "components");
  const patterns = readdirSync(componentsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  const entries: string[] = [];

  for (const pattern of patterns) {
    const bootstrap = escapeTemplateString(
      getComponentSource("bootstrap", pattern),
    );
    const antd = escapeTemplateString(getComponentSource("antd", pattern));
    const mantine = escapeTemplateString(
      getComponentSource("mantine", pattern),
    );

    entries.push(`  "${pattern}": {
    bootstrap: \`${bootstrap}\`,
    antd: \`${antd}\`,
    mantine: \`${mantine}\`,
  }`);
  }

  const content = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-snippets.ts
 * Run: pnpm generate-snippets
 */

export const codeSnippets: Record<
  string,
  { bootstrap: string; antd: string; mantine: string }
> = {
${entries.join(",\n")}
};
`;

  writeFileSync(OUTPUT_FILE, content, "utf-8");
  console.log(`Generated ${OUTPUT_FILE}`);
  console.log(`Patterns: ${patterns.length}`);
  console.log(`Frameworks: bootstrap, antd, mantine`);
}

generateSnippetTemplates();
